### ISSUE TITLE
 The eth-addr converted by the qx utility is not the same as the address imported into the wallet

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#231]
This is the `entropy` generated by qx:
`8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c`

### Create the EC private key from seed

- meer-addr

  `./qx mnemonic-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c|./qx mnemonic-to-seed|./qx ec-new|./qx ec-to-public|./qx ec-to-addr`
  MmRoVX8qkpFWLL6TJSoYBENkYNyLaRqwzg8

- eth-addr

  `./qx mnemonic-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c|./qx mnemonic-to-seed|./qx ec-new|./qx ec-to-public|./qx ec-to-ethaddr`
  0x391DA25f35f33ae7d29F22B4eF51513D5D016142

### Create the EC private key from entropy

- meer-addr

  `./qx ec-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c|./qx ec-to-public|./qx ec-to-addr`
  MmdEyQ8WLXko61ntKdpdSvUzsTs8z2MKnhU

- eth-addr

  `./qx ec-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c|./qx ec-to-public|./qx ec-to-ethaddr`
  0x813cD629155156Ad9edC25A431C0132C843e59E7

### Import mnemonic into wallet

`./qx mnemonic-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c`   
market must tired head space poverty visit pistol buddy tissue debate year letter father alley nurse route riot wish what screen face anchor mass

The meer-addr in wallet is `MmRoVX8qkpFWLL6TJSoYBENkYNyLaRqwzg8`, matching.

But, the eth-addr in wallet is `0xF7f29E8df5c46E2d1747029Fc9b6E9281C8c0415`, neither `0x391DA25f35f33ae7d29F22B4eF51513D5D016142`(from seed) or `0x813cD629155156Ad9edC25A431C0132C843e59E7`(from entropy directly).

What is the problem, am I missing any steps?

**Comment by jamesvan2019** [comment]
- meer-addr

  `./qx mnemonic-new 8832438ab50d05523d352b1d7c58e17f7808a741a4bcbc9747f27cec18a3021c|./qx mnemonic-to-seed|./qx ec-new|./qx ec-to-public|./qx ec-to-addr`
  MmRoVX8qkpFWLL6TJSoYBENkYNyLaRqwzg8

**Comment by blocklee** [comment]
Ok, I understand. Thanks.
