### ISSUE TITLE
The left balance of TxTypeCrossChainImport transaction flying

### ISSUE THREAD

**Issue by blocklee** [Qitmeer/qng#249]
My ethaddr has 1001 Meer balance which is transferred  form UTXO.  The txid is `4fff8c7827fedcea5fc60152a94edeee8c391073a109beb3dbdd72929faebb01`.

I create a TxTypeCrossChainImport transaction use qx, imported 0.1 Meer form EVM to UTXO following the qx README.md.  But the left 1000.9 Meer balance flying.

Since the cli-cmd `sendRawTx <signedRawTx>` not work, I send the tx using the command following the [docs example](https://qitmeer.github.io/docs/en/json-rpc-api/sendrawtransaction/#example):

```bash
curl -sku "qitmeer:qitmeer123" -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"1.0","method":"sendRawTransaction","params":["010000000101bbae9f9272dddbb3be09a17310398ceede4ea95201c65feadcfe27788cff4ffeffffff0201000001000080969800000000001976a9145f01d8c2b03b3a2b7bcf1a41e4d2bd984937eeb788ac00000000000000003e2d55630180354d6b36713636596835347a6558375534525367554e53536f787968656b424474554b444343557a4733575064595a4657465975566549483045022100c34dae6c2d5f4de3bf988c5a82bba06d1117aecd43962ec157c58849f7a2f0f802204637d27c3aaf850181d775739958a5e7728c1105110895a4b84f4824b50c25ab01", true],"id":1}' https://127.0.0.1:18131
```

the result:

```bash
{
"jsonrpc": "2.0",
"id": 1,
"result": "43e041e3ab2fff1278c3378a137aadfa7b62053c212c0a3fbda99d02b9d62003"
}
```

The tx is included in block [1229119](https://meerscan.io/block/90bf51a89c211812b9210e4f4313105103f87f0f243fb7e6a211138c8fe35349)

 I checked the block data of 1229119, find that the full left balance of the TxTypeCrossChainImport transaction maybe is given directly to miner as a fee！Is this a BUG?

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/32875657/197403631-2d201505-eb7a-439d-96da-28b14a735d1b.png">

**Comment by dindinw** [comment]
The `TxTypeCrossChainImport` transaction means `EVM balance to UTXO` which is intended to convert all balance, the changes will be  calculated as the miner fee if the `allowHighFee` argument  is set to be true forcefully.  It's not a bug, Please transfer your balance to another balance address ( the `0x` address) before you send a `TxTypeCrossChainImport` tx if you **don't want to convert all the balance amount** of the address.
