### ISSUE TITLE
TestEVM fail

### ISSUE THREAD

**Issue by lochjin** [Qitmeer/qng#47]
Reproduce example:
https://github.com/Qitmeer/qng/runs/5210110682?check_suite_focus=true#step:6:3430
https://github.com/Qitmeer/qng/runs/5163827045?check_suite_focus=true#step:6:3424

Error location: 
func TestEVM(t *testing.T)

Error info:
` evm_test.go:46: GetBalance failed:Post "http://127.0.0.1:18545": dial tcp 127.0.0.1:18545: connect: connection refused`

**Comment by jamesvan2019** [comment]
Fix By PR #69
