### ISSUE TITLE
how to create a txid for transfering asset meer utxo to evm

### ISSUE THREAD

**Issue by ghost** [Qitmeer/qng#709]
I just setuped a privnet node and miner and i am trying to transfer my mined meer utxo to evm meer. When i read your documentation then there is the way to transfer them but you are taking a random txid. How can i generate a txid for my transaction.

**Comment by dindinw** [comment]
Maybe the documentation here is not precise enough, where is not a random txid, It try to convert a UTXO (u own it so you should know the tx and txindex) into a EVM balance.

**Comment by ghost** [comment]
Can you help me to get the txid from the UTXO as I haven't came across any cli command or anything. 
What I understood is txid is one of the UTXO owned by any address. Is my assumption correct?

**Comment by dindinw** [comment]
I think you should understand what an UTXO is (such as https://learnmeabitcoin.com/technical/transaction/input/vout/
https://learnmeabitcoin.com/technical/transaction/utxo/) 
You may also like to read some doc from 
- https://qitmeer.github.io/docs/en/json-rpc-api/getrawtransaction/
- https://qitmeer.github.io/docs/en/json-rpc-api/getutxo/

**Comment by ghost** [comment]
I'm following these steps for transfering funds from utxo to evm account -->

1. `./qx tx-encode -v 1 -i ed921734f15494ef279f77eed69b95e3ee381d1918bd0602e409554bb78203ec:0:4294967295:pubkeyhash -l 0 -o Rk415Wsze5Hic41WhVt5ZDcRaUtjyBkoYZ18Uj6pbZ2DbcdK6WEVt:2.101:1:pubkey -o RmRZ6m5Zyh5oJR6om7Kx489S2NL1DFNWWmG:2.1849:0:pubkeyhash | ./qx tx-sign -k 3a4aaf385452180ec3a3fe10da6b4b96e08377818ac34a67f8a6edfc446e28fb -n privnet
` 
2. `./qitmeer-cli sendRawTransaction 0100000001ec0382b74b5509e40206bd18191d38eee3959bd6ee779f27ef9454f1341792ed00000000ffffffff01010020df850c0000000023210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016ac00000000000000004fcc5566016a47304402201fecb1641fb1685dede047af88057d5275cf589956e19efda4cb54d907dd824702201ac80d27982ae932fc73ba413749c627369b27a8163b102e5724d8df83c6c6f001210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016`

then i am getting this error -> 
`[ERROR] Failed to process transaction       module=txmanager err="transaction 649f99616ce13b483dbe136a7fb17a630a0ba7ceb1814bf98b088dcbec551e23 has 39571405220 fee which is above the allowHighFee check threshold amount of 24900000 (= 249 byte * 10000 atomMEER Asset/kB * 10000)"
`

**Comment by frankcrypto2023** [comment]
Refer to [https://github.com/Qitmeer/qng/tree/main/cmd/qx#txtypecrosschainexporttx-from-meer-to-evm](https://github.com/Qitmeer/qng/tree/main/cmd/qx#txtypecrosschainexporttx-from-meer-to-evm)
The txid `ed921734f15494ef279f77eed69b95e3ee381d1918bd0602e409554bb78203ec` has 400 MEER, but your outputs only costs 2.101+2.1849 , the left will be treated as mining fee, the node security interception your request, you can add more output receive the amount or if you allow high fee, you can do this add a pameter `true`

`./qitmeer-cli sendRawTransaction 0100000001ec0382b74b5509e40206bd18191d38eee3959bd6ee779f27ef9454f1341792ed00000000ffffffff01010020df850c0000000023210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016ac00000000000000004fcc5566016a47304402201fecb1641fb1685dede047af88057d5275cf589956e19efda4cb54d907dd824702201ac80d27982ae932fc73ba413749c627369b27a8163b102e5724d8df83c6c6f001210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016 true`


> I'm following these steps for transfering funds from utxo to evm account -->
> 
> 1. `./qx tx-encode -v 1 -i ed921734f15494ef279f77eed69b95e3ee381d1918bd0602e409554bb78203ec:0:4294967295:pubkeyhash -l 0 -o Rk415Wsze5Hic41WhVt5ZDcRaUtjyBkoYZ18Uj6pbZ2DbcdK6WEVt:2.101:1:pubkey -o RmRZ6m5Zyh5oJR6om7Kx489S2NL1DFNWWmG:2.1849:0:pubkeyhash | ./qx tx-sign -k 3a4aaf385452180ec3a3fe10da6b4b96e08377818ac34a67f8a6edfc446e28fb -n privnet `
> 2. `./qitmeer-cli sendRawTransaction 0100000001ec0382b74b5509e40206bd18191d38eee3959bd6ee779f27ef9454f1341792ed00000000ffffffff01010020df850c0000000023210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016ac00000000000000004fcc5566016a47304402201fecb1641fb1685dede047af88057d5275cf589956e19efda4cb54d907dd824702201ac80d27982ae932fc73ba413749c627369b27a8163b102e5724d8df83c6c6f001210212230a1b72b34a732ecb221186d95ebd61f055cfbff8810fa0642cbadce68016`
> 
> then i am getting this error -> `[ERROR] Failed to process transaction module=txmanager err="transaction 649f99616ce13b483dbe136a7fb17a630a0ba7ceb1814bf98b088dcbec551e23 has 39571405220 fee which is above the allowHighFee check threshold amount of 24900000 (= 249 byte * 10000 atomMEER Asset/kB * 10000)" `

**Comment by dindinw** [comment]
The issue has been closed due to no further input in a few days. Please reopen it if you have any further questions. @traderbro
