### ISSUE TITLE
Why the miner is stopped automatically after around 1148 or 1150 blocks mining in privnet.

### ISSUE THREAD

**Issue by dev001111** [Qitmeer/qng#719]
When i am starting the miner and node both on local with this `qng` binary then after 1140  blocks miner stopped automatically in `privnet`. I tried so many times sometimes it's going to 1150-1160 and stops why?

**Comment by dindinw** [comment]
Could you please provide the version of the QNG you are using? 
You can use this line of command to display
```./bin/qng -V```
BTW, How do you know the miner is stopped? It is normal for block producing to slow down due to the difficulty adjustment algorithm.

**Comment by frankcrypto2023** [comment]
Please use latest miner and node
Miner can set 2 parameters in config 
- `task_interval=3000`
- `timeout=30`

**Comment by dindinw** [comment]
Please refer to the changes here #721 , which may help your problem.

**Comment by ravin-bhambhu07** [comment]
@dindinw this is my qng version `qng version 1.2.0+dev-4d595ec-dirty`

**Comment by dindinw** [comment]
We believe that this problem is caused by too frequent miner client submitting, which causes the difficulty to increase too quickly to produce blocks. It can be solved by modifying the default configuration by referring to the method mentioned above #721 . You can use the latest code, or manually modify your local configuration files. The issue has been closed. If you have further questions please open it again.

**Comment by dev001111** [comment]
i changed these configs `task_interval=3000
timeout=30` but still it's not working

**Comment by dindinw** [comment]
First of all, please distinguish between "stop of block producing" and "difficulty of block producing". The two are different. Please also provide more details for us to help analyze, such as the node version and node log output.

**Comment by dev001111** [comment]
<img width="1792" alt="Screenshot 2024-06-13 at 9 42 54 AM" src="https://github.com/Qitmeer/qng/a
<img width="1792" alt="Screenshot 2024-06-13 at 9 43 10 AM" src="https://github.com/Qitmeer/qng/assets/171344914/26f4b63f-cd2f-4157-9031-53e1c91f774c">
ssets/171344914/2025fed0-ebc6-4611-a5c5-f506da3859fb">
<img width="1792" alt="Screenshot 2024-06-13 at 9 43 24 AM" src="https://github.com/Qitmeer/qng/assets/171344914/946b3966-965b-4884-a973-1a548fb3afba">

**Comment by dindinw** [comment]
I don't see a problem here, the difficulty adjustment algorithm is working exactly as expected. The default time target of the private network is 30 seconds. If you think it is too long, you can manually adjust this parameter. 
https://github.com/Qitmeer/qng/blob/main/params/params_privnet.go#L24
