### ISSUE TITLE
How to setup grafana for qng.

### ISSUE THREAD

**Issue by dev001111** [Qitmeer/qng#743]
I was trying to setup grafana for qng. According to qng metrics readme file i was setup a influxdb on my local system i was created a database also into that but when i am starting the node then i am getting the error `2024-07-30|12:11:49.622 [WARN ] Unable to send to InfluxDB           err="{\"error\":\"database is required\"}\n"`. Please provide the solution regatding the setup of grafana.

**Comment by dev001111** [comment]
i am following this repo `https://github.com/Qitmeer/qng.git`.

**Comment by lochjin** [comment]
> I was trying to setup grafana for qng. According to qng metrics readme file i was setup a influxdb on my local system i was created a database also into that but when i am starting the node then i am getting the error `2024-07-30|12:11:49.622 [WARN ] Unable to send to InfluxDB err="{\"error\":\"database is required\"}\n"`. Please provide the solution regatding the setup of grafana.

Please ensure that these command-line parameters are enabled:
./qng --metrics --metrics.expensive  --evmenv="--metrics.influxdb"
