### ISSUE TITLE
Error: "Parents gap is 12.000000 which is more than 10" - Privnet Node Not Running

### ISSUE THREAD

**Issue by dev001101** [Qitmeer/qng#763]
I'm encountering an error with my Qitmeer privnet node. The error message states: [ERROR] Parents gap is 12.000000 which is more than 10 module=DAG. This error appears to prevent the node from running correctly. I would like to understand what causes this error and how to resolve it to get my privnet node running again. Any guidance or troubleshooting steps would be appreciated.

Let me know if you want to add more details or make any adjustments!

@dindinw can you please help me with this.

**Comment by s-h-ubham** [comment]
Facing the same issue if someone can help it will be helpful

**Comment by dindinw** [comment]
Please provide version information and node startup parameters you are using, thanks

**Comment by dev001101** [comment]
Hi @dindinw, this is the command for running node `./qng --privnet --rpclisten=0.0.0.0:38131 --port=38130 --notls --rpcuser=test --rpcpass=test --miner --miningaddr=$minning_address --generate --walletpass=test --evmenv="--http --http.port=18545 --http.addr=0.0.0.0 --http.api=net,web3,eth,qng --ws --ws.port=18546"  --miningstatesync`
 and version is `1.2.0+dev-9c1f674-dirty`

**Comment by dindinw** [comment]
1.  9c1f674 is not a publicly visible commit  in our repo. and dirty means some local changes exist. please keep using the release version or the latest dev version for your testing.  
2.  normally we don't  use `--miningstatesync` for the privnet.

**Comment by dev001101** [comment]
Hi @dindinw, i just changed block creation time to `1 sec` for privnet nothing else that's why these are my local changes.Do you have any idea why this happens.

**Comment by dindinw** [comment]
1. The block creation time has been set to 1 sec for privnet by default in 2.0 version. 
Please use the 2.0 version https://github.com/Qitmeer/qng/tree/release/2.0.0
or the latest dev version
2. don't use `--miningstatesync` for the privnet.

**Comment by dev-580** [comment]
Hi @dindinw  i am facing the same issue here... and  i have setup my own 3 nodes in testnet not privnet but i am still facing the same issues after sometime . Any idea why this is happening .

**Comment by dindinw** [comment]
@Abhishek-ATR580 
Basic information you need to provide
1. detail build version (output of `qng -V`)
2. the start-up parameter of your running node.

**Comment by dev-580** [comment]
@dindinw  here is the command i am using 
```
 ./qng
      --testnet
      --notls
      --rpcuser=test
      --rpcpass=test
      --miner
      --miningaddr=${MINNING_ADDRESS}
      --generate
      --walletpass=test
      --evmenv="--http --http.port=18545 --http.addr=0.0.0.0 --http.api=net,web3,eth,qng --ws --ws.origins=* --ws.port=18546 --http.corsdomain=* --http.vhosts=* --http.corsdomain=*"
      --miningstatesync
```
  and qng version is 
`  qng version 1.2.0+release-aa3e121 (Go version go1.22.3)
`
everything comes down to this function 
```
// Checking the layer grap of block
func (bd *BDAG) checkLayerGap(parentsNode []IBlock) bool {
	if len(parentsNode) == 0 {
		return false
	}

	pLen := len(parentsNode)
	if pLen == 0 {
		return false
	}
	var gap float64
	if pLen == 1 {
		return true
	} else if pLen == 2 {
		gap = math.Abs(float64(parentsNode[0].GetLayer()) - float64(parentsNode[1].GetLayer()))
	} else {
		var minLayer int64 = -1
		var maxLayer int64 = -1
		for i := 0; i < pLen; i++ {
			parentLayer := int64(parentsNode[i].GetLayer())
			if maxLayer == -1 || parentLayer > maxLayer {
				maxLayer = parentLayer
			}
			if minLayer == -1 || parentLayer < minLayer {
				minLayer = parentLayer
			}
		}
		gap = math.Abs(float64(maxLayer) - float64(minLayer))
	}
	if gap > MaxTipLayerGap {
		log.Error(fmt.Sprintf("Parents gap is %f which is more than %d", gap, MaxTipLayerGap))
		return false
	}

	return true
}
```
and after is get this error 
```
if gap > MaxTipLayerGap {
		log.Error(fmt.Sprintf("Parents gap is %f which is more than %d", gap, MaxTipLayerGap))
		return false
	}
```
complete network stops to sync and mine ... and every node gets same  error and stops mining .
and when i restarts the issue still remains.

**Comment by dindinw** [comment]
@Abhishek-ATR580 
Please run the following commands on your local node and provide with the output:
1.  the state root info
```bash
curl -s -k -u test:test -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"getStateRoot","params":[-1,true],"id":1}' https://127.0.0.1:18131|jq .
```

2.  the peers info
```bash
curl -s -k -u test:test -X POST -H 'Content-Type: application/json' --data '{"jsonrpc":"2.0","method":"getPeerInfo","params":[false,""],"id":null}' http://127.0.0.1:18131|jq .
```
I suppose u have `curl` and `jq` installed.

**Comment by dev-580** [comment]
@dindinw i am runnig my 5 node testnet and i am not connecting to already runnjng testnet on Qitmeer for testing purpose

**Comment by dindinw** [comment]
Generally speaking, we call the `testnet` the public testnet, so this situation will not work.

**Comment by dev-580** [comment]
@dindinw can u tell me when this parent gap issue may come or what are things that need to be in check so i don't get this error ....and also  as you are saying that `testnet` is for `public testnet` so do i need to run or pass some other  flag as i don't want to connect to already running `testnet`. I am trying to set up my own network with 5 to 6 nodes for now .

**Comment by dindinw** [comment]
Please use `--privnet` for the private network.  the `--testnet` is for connecting with the public testnet only.

**Comment by dev-580** [comment]
Hello @dindinw  the error also occured for `--privnet` too . I think the blocks are getting mined very fast.

**Comment by dindinw** [comment]
@Abhishek-ATR580 
We have tested `--privnet` setting both on latest dev version and 1.2 release version. Mining and network are normal && No obvious abnormalities were found for more than 24 h.

1. Please provide us your `peerinfo` output when your problem occurs.  
2. You can try to use the latest dev version ( build source from the `dev/2.0` branch) and check if your problem still exists

But first you have to keep one thing in mind that the consensus protocol requires good inter-connection between nodes, which is a prerequisite for the protocol to work well. Therefore, before multi-node block production can work normally, we must first ensure that multi-node synchronization works well, especially when the block production time is set to be very small and the synchronization requirements are very high.

**Comment by dev-580** [comment]
@dindinw by going through the below code snippet I got to know that layer gap error is coming from here.. and by going into this code it is  clear that the gap which is being calculated  is coming greater than MaxTipLayerGap but my question now is how can we overcome this error .. what can be the possible scnerios in which this error will come and in which it will not ? How can i tackle this error so in future this error never comes ?

```
// Checking the layer grap of block
func (bd *MEERDAG) checkLayerGap(parentsNode []IBlock) bool {
	if len(parentsNode) == 0 {
		return false
	}

	pLen := len(parentsNode)
	if pLen == 0 {
		return false
	}
	var gap float64
	if pLen == 1 {
		return true
	} else if pLen == 2 {
		gap = math.Abs(float64(parentsNode[0].GetLayer()) - float64(parentsNode[1].GetLayer()))
	} else {
		var minLayer int64 = -1
		var maxLayer int64 = -1
		for i := 0; i < pLen; i++ {
			parentLayer := int64(parentsNode[i].GetLayer())
			if maxLayer == -1 || parentLayer > maxLayer {
				maxLayer = parentLayer
			}
			if minLayer == -1 || parentLayer < minLayer {
				minLayer = parentLayer
			}
		}
		gap = math.Abs(float64(maxLayer) - float64(minLayer))
	}
	if gap > MaxTipLayerGap {
		log.Error(fmt.Sprintf("Parents gap is %f which is more than %d", gap, MaxTipLayerGap))
		return false
	}

	return true
}
```

**Comment by dindinw** [comment]
your question answered on #816
