### ISSUE TITLE
confusion in the config file 

### ISSUE THREAD

**Issue by varshney565** [Qitmeer/qng#806]
hello developers,
I need some help in the config file in 
``params > params_testnet.go`` why ``ReduceMinDifficulty``  is set to ``false``.

In bitcoin they are setting this value to be true for all the nets except the ``mainnet``.
Is there any specific reason for setting it to ``false`` in ``Qitmeer``
@dindinw @jdowdell @wyonghao @0xxfu @blocklee

**Comment by dindinw** [comment]
`ReduceMinDifficulty == false` means that the difficulty adjustment cannot be lowered to the initial setting minimum difficulty and the network will not lower the required minimum difficulty after a long period of time without finding a block..  This is QNG's setting default, there seems to be no ambiguity here.
