### ISSUE TITLE
how to enable GPU mining.

### ISSUE THREAD

**Issue by varshney565** [Qitmeer/qng#815]
I would like to inquire about how to enable GPU mining with Qitmeer or if there are specific configurations or a separate miner required to leverage GPU resources.
Could you please provide guidance on how to activate GPU mining, and, if possible, the correct command or configuration to start GPU mining? Any assistance with this would be highly appreciated.
@dindinw

**Comment by varshney565** [comment]
I am using the following command
```./qitmeer-miner -C config.conf```

**Comment by dindinw** [comment]
The GPU mining is not support officially on Qitmeer mainnet && testnet,  The legacy code for GPU mining in the current project is a historical issue. Please don't use the GPU mining.

**Comment by varshney565** [comment]
Is there any specific reason that Qitmeer does not support GPU mining?

**Comment by Ayushoo07** [comment]
So @dindinw can i run gpu mining on privnet or not ? and why gpu mining  is not supported ?

**Comment by dindinw** [comment]
@Ayushoo07 
you can run gpu mining for testing purposes on your own privnet,  but it's not guaranteed to be supported or maintained.  
Historically, GPU mode has been used in [the pre-public testnet to encourage participation](https://github.com/Qitmeer/qitmeer/blob/master/TESTNET_REWARD.md) . This mode is now obsolete and will not be supported in the official network and test network.

**Comment by Ayushoo07** [comment]
@dindinw ok got it so can you guide me how can i test gpu mining on privnet and what versions of qng and qitmeer-miner support that .

**Comment by dev-580** [comment]
Hello @dindinw as reading the above conversations and knowing that gpu mining is not supported , how can i mine using asic and which asic device should i use ?

**Comment by varshney565** [comment]
@dindinw how can I mine using asic ?
