### ISSUE TITLE
Confusion in parent selection logic when block is added to dag ?

### ISSUE THREAD

**Issue by Devloper0007** [Qitmeer/qng#816]
Hello, @dindinw 

I was reviewing the logic for how parent blocks are added and how the layer gap is checked in Qitmeer, and I found the implementation quite interesting. However, I encountered some confusion regarding the layer gap validation in the tips.go file.

In the function getValidTips:
```
func (bd *MeerDAG) getValidTips(limit bool) []IBlock {
	temp := bd.tips.Clone()
	mainParent := bd.getMainChainTip()
	temp.Remove(mainParent.GetID())
	var parents []uint
	if temp.Size() > 1 {
		parents = temp.SortHeightList(true)
	} else {
		parents = temp.List()
	}

	tips := []IBlock{mainParent}
	tipsM := map[string]struct{}{}

	for i := 0; i < len(parents); i++ {
		if mainParent.GetID() == parents[i] {
			continue
		}
		block := bd.getBlockById(parents[i])
		if math.Abs(float64(block.GetLayer())-float64(mainParent.GetLayer())) > MaxTipLayerGap {
			continue
		}
		_, exist := tipsM[block.GetHash().String()]
		if exist {
			continue
		}
		tips = append(tips, block)
		tipsM[block.GetHash().String()] = struct{}{}
		if limit && len(tips) >= bd.getMaxParents() {
			break
		}
	}
	return tips
}

```
In this function, the difference in layers is calculated by comparing each potential parent block with the main parent. If the layer difference exceeds MaxTipLayerGap, that parent block is excluded. However, in the checkLayerGap function:
```

func (bd *MeerDAG) checkLayerGap(parentsNode []IBlock) bool {
	if len(parentsNode) == 0 {
		return false
	}

	pLen := len(parentsNode)
	if pLen == 0 {
		return false
	}
	var gap float64
	if pLen == 1 {
		return true
	} else if pLen == 2 {
		gap = math.Abs(float64(parentsNode[0].GetLayer()) - float64(parentsNode[1].GetLayer()))
	} else {
		var minLayer int64 = -1
		var maxLayer int64 = -1
		for i := 0; i < pLen; i++ {
			parentLayer := int64(parentsNode[i].GetLayer())
			if maxLayer == -1 || parentLayer > maxLayer {
				maxLayer = parentLayer
			}
			if minLayer == -1 || parentLayer < minLayer {
				minLayer = parentLayer
			}
		}
		gap = math.Abs(float64(maxLayer) - float64(minLayer))
	}
	if gap > MaxTipLayerGap {
		log.Error(fmt.Sprintf("Parents gap is %f which is more than %d", gap, MaxTipLayerGap))
		return false
	}

	return true
}
```
Here, the layer gap is calculated as the absolute difference between the maximum and minimum layer among all parent nodes. It is not necessarily based on the main parent.

To clarify my confusion, consider the following case:

    The main parent is at layer 10.
    The minLayer_parent is at layer 5.
    The maxLayer_parent is at layer 18.

In this scenario, when running getValidTips, both the minLayer_parent and maxLayer_parent would be considered valid because the difference between their layers and the main parent's layer is less than or equal to MaxTipLayerGap. However, in the checkLayerGap function, the absolute difference between maxLayer and minLayer (i.e., 18 - 5 = 13) would exceed the MaxTipLayerGap of 10, causing it to fail the validation.

Could you please clarify the rationale behind this implementation? Is there an interpretation I might be missing, or is there a specific reason for these differing methods of layer gap validation?

**Comment by dindinw** [comment]
@AyushSingh8x 
1.  First of all, thank you for your concern about the code of this project. In fact, this project has lacked similar in-depth discussions, although this project has been conducted in an open source manner from the first day.
2.  The logic here is self-consistent and not contradictory. The two methods you cited target different objects. The first method is to conduct consensus judgment from the perspective of the main chain, while the second method is to conduct consensus judgment from the perspective of any block node. So the example you gave does not validated. 
3. In other words, block nodes need to satisfy both 2 consensus perspectives.

**Comment by Devloper0007** [comment]
@dindinw  Thanks for the clarification . How can we overcome this error then ? Also what can be the scenerios in which this issue can arise ?

**Comment by dindinw** [comment]
We cannot reproduce the problem you encountered using the private network. This error essentially means that the block was rejected by the consensus. This itself means that the consensus is working. So if you think the consensus is not working properly, our understanding is that the consensus is working, further details may be required to verify special circumstances in your environment.

**Comment by Devloper0007** [comment]
Yeah @dindinw  i agree that the consensus mechanism is functioning as expected with no apparent issues. However, when any node in the network encounters this error, it ceases block production, which ultimately causes all nodes in the network to halt block production as well . i think this should not halt further block production ?

and according to you whats the scenerio when the block passes one check and fails on another?

**Comment by dindinw** [comment]
@AyushSingh8x 
Yes, you are right, the key to consensus is to prevent what is wrong and maintain what is right. But when an erroneous consensus occurs, it may be a very challenging task to automatically enable the erroneous nodes to get rid of the erroneous state. But first, it is necessary to ensure that the correct consensus can continue to work, that is, there will not be a situation where all nodes stop producing blocks. Of course, this condition needs to meet theoretical and environmental prerequisites, such as the premise of 51% computing power consensus, Sybil attack Scenarios and malicious network isolation scenarios, etc.
But in short, consensus first needs to ensure that the network continues to operate. That is, it is necessary to ensure that most nodes can continue to operate. This is especially true for Permissionless networks, so it is possible for a single node to fall into a state that cannot automatically recover, but the failure of all nodes should not occur. At least this is the design and implementation goal of the consensus.
So if you can construct and reproduce a scenario where all nodes fail, then we may be able to find bugs and further optimize the system to solve possible problems. In short, there may be bugs in the implementation and problems in the operating environment, but there are essential differences between Permissioned networks and permissionless networks. This is a network characteristic and needs to be used as a prerequisite to check whether it works.

**Comment by dindinw** [comment]
issue is closed since  there has been no more input for a long time
