### ISSUE TITLE
ASIC miner

### ISSUE THREAD

**Issue by ghost** [Qitmeer/qng#825]
@dindinw  Which ASIC miner is best suited for mining Qitmeer Mainnet?

**Comment by dindinw** [comment]
Questions about ASIC miner, please go to [the qitmeer.io website](https://qitmeer.io) for help.

**Comment by Devloper0007** [comment]
@dindinw, I was also attempting to run an ASIC miner but couldn’t find any documentation on which device to use. I'm asking here because I couldn’t find a discussion channel on the [Qitmeer website](https://qitmeer.io/) for this.
